### ISSUE TITLE
Remove react hot reload?

### ISSUE THREAD

**Issue by dlebedynskyi** [peter-mouland/react-lego#11]
See  https://github.com/gaearon/react-hot-boilerplate/issues/97#issuecomment-249862775

it looks like react hot reloader is dead. In a good way. Btw really great project 👍

**Comment by peter-mouland** [comment]
hmmm, interesting discussion in that link, I can see the reason for his _pivot_!

I'll have to let this sleep on it and also see how the community Reacts.

**Comment by dlebedynskyi** [comment]
@peter-mouland yap. just giving heads up. It looks like a lot of work he plans to cover in create react app. 

What is missing is server stuff since apparently not going to happen https://github.com/facebookincubator/create-react-app/pull/500#issuecomment-242764176

Imho I'd really love to see create-react-app + universal part

**Comment by peter-mouland** [comment]
yeah, I'm sure they'll get round to it, sounds like stability is key t start with which is fair.

There seems to be a few great boiler-plates/helpers out there that are missing that _sometimes_ essential ingredient of being universal.  when i have the time i'll take start of this app back one level and do a branch to show client-side react vs universal react.

**Comment by ngoctranfire** [comment]
I would like to say that one of the things that we forget is that most of the time, react-hot-loader is not a standalone that is used by itself. With stores/redux in mind, this makes hot-reloading a little bit trickier. I think having an example that branches off from the redux branch will make it more friendly, and maybe one that is branched off the react-router-4 as well? There are so many moving parts at any time.

**Comment by peter-mouland** [comment]
Thanks for the discussion guys. I'm going to leave it in at least until React comes with it baked in.

The other branches makes sense as suggestions so i've raised issues for those (PR's welcome!)  Hopefully it'll be as easy as the webpack2-rhl branch which just worked!
