### ISSUE TITLE
[master/webpack2-*] 'npm start` use development build

### ISSUE THREAD

**Issue by dlebedynskyi** [peter-mouland/react-lego#13]
_issue come from master branch but very visible in webpack2-hrm branch_

Steps to reproduce 
1. set your NODE_ENV to development
2. run `npm run start:dev` 
3. kill it and run `npm run build:server` and `npm run start` . 
4. Notice env still set to `development`.  _`build` does sets NODE_ENV to production but it does so after `build:server` in `prestart`_
5.  open localhost:3000 with network - watch /__webpack_hrm request.

Expected 
Manage node_env more consistent. 

Suggestion 
```json
  "prestart": "rm -rf compiled && npm run build:server && npm run build",
  "prestart:dev": "NODE_ENV=development npm run build:dev",
    "build": "NODE_ENV=production webpack --config src/config/webpack.config.prod.js --optimize-minimize",
    "build:dev": "NODE_ENV=development webpack --config src/config/webpack.config.dev.js",
    "build:server": "NODE_ENV=production webpack --config src/config/webpack.config.server.js",
```

**Comment by peter-mouland** [comment]
interesting bug, thanks for pointing it out.

since, according the the `environment.js`, setting NODE_ENV to 'development' is default, I assume, setting the only `build` and `build:server` scripts to include prod would be enough.  

Would you agree or would that still cause inconsistencies for your use case?

**Comment by dlebedynskyi** [comment]
`enviroment.js` will set to default if not env var is not set in process. but if it is set - like after `build` it stays production, correct?

**Comment by peter-mouland** [comment]
thanks for pointing out the problems - i've updated the code to include the node_env=production.  I've decided to leave off the env for dev to allow a bit more flexibility. hopefully this will be ok - if it proves to still be problematic in the future i'll have to rethink it!
