### ISSUE TITLE
On Branch css-modules, webpack build:server command fails

### ISSUE THREAD

**Issue by ngoctranfire** [peter-mouland/react-lego#19]
Hi,
I noticed that when I tried to run npm run build:server on the css-modules branch, it breaks and that does not allow me to do a good npm run start. I think that the reason this is happening is related to this issue with https://github.com/css-modules/css-modules-require-hook/issues/67. I'm working on trying to see if I can fix it, but maybe someone who knows this stuff better may be able to give me a helping hand on this.

**Comment by peter-mouland** [comment]
good spot, not sure when that crept in.  It looks like a mix up in css-modules-require-hook dependencies or they are accidentally run tests after we install the package. 

I've raised an issue with them also: https://github.com/css-modules/css-modules-require-hook/issues/79

**Comment by ngoctranfire** [comment]
This error also appears on the svg branch as well I believe it is the same type of error.

**Comment by peter-mouland** [comment]
I've fixed the css-modules branch by bumping the version number and by stop using the `preset` option
