### ISSUE TITLE
DEBUG=lego:* Error

### ISSUE THREAD

**Issue by govind999** [peter-mouland/react-lego#2]
When i try to start, I am getting error here DEBUG=lego:* on windows, anyway i removed that tested all features.

One more question, where is the branch which has all integrated? your master branch is not having the redux integrated.

Thanks.

**Comment by peter-mouland** [comment]
ok thanks for raising that, i'll have to double check that on windows.

I haven't create a `complete` branch yet, but will do soon 👍

**Comment by peter-mouland** [comment]
windows should be fixed with https://github.com/peter-mouland/react-lego/commit/2acaaf6713db50caf7eca079afab2be540f99391

let me know if you find anything else as i don't actively develop on windows
