### ISSUE TITLE
Hot-reload branch does not work as expected

### ISSUE THREAD

**Issue by ngoctranfire** [peter-mouland/react-lego#24]
Sorry to be filing so many bugs and such, but I really like your project and its actually helped me to learn redux by the pieces and get to understand the numerous moving parts that are so confusing to me. 
On your react-hot-loader branch, just by itself, I noticed that it just doesn't work correctly. When I make a change, the changes are not updated automatically. Also, I was getting this error at the beginning: not sure if it's related.

```HMR] Update check failed: Error: Manifest request to /6a46934f57636f62dc58.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://localhost:3000/app.js:34:23)```

**Comment by peter-mouland** [comment]
keep them coming :)
I have noticed things go wrong after seemingly simple rebase from master - i should i guess write a specific e2e test to prove each branches purpose to stop that from happening.

I haven't seen the problem you mention, but i'll take a look and try to replicate it.

**Comment by peter-mouland** [comment]
![out](https://cloud.githubusercontent.com/assets/1727939/19067743/6a5abd76-8a17-11e6-89c0-e7364b998572.gif)

This is hot-reloading working for me... granted I get a different error!

**Comment by dlebedynskyi** [comment]
> granted I get a different error!
this is known issue with hot reloading and react router v2.

**Comment by peter-mouland** [comment]
yeah, i'm tempted to ignore it in the hope the the final RHL v3 and the final RR v4 aren't far away!

in the mean-time 🙉 🙈

**Comment by peter-mouland** [comment]
I haven't seen this bug still so will close the branch.. if you can show me how to replicate it in reat-lego, then we can reopen
