### ISSUE TITLE
 "webpack-dev-server": "^1.14.1", in Webpack v2 HRM

### ISSUE THREAD

**Issue by dlebedynskyi** [peter-mouland/react-lego#27]
webpack-dev-server 1.14 requires webpack 1.

webpack-dev-server now has 2.1.0-beta.8 that support webpack 2. 
_Note: there are breaking changes in beta3_

Also "purifycss-webpack-plugin": "^2.0.3", required webpack 1

**Comment by peter-mouland** [comment]
I'm not 100% sure what the issue is, I guess these are just new versions to be aware off?

The webpack dev server is only used for the client-side only branch, which means I haven't needed it for any webpack 2 branches.

I've noticed i'm not actually using purifycss! so for now, i'll just remove it from the package.

**Comment by dlebedynskyi** [comment]
@peter-mouland  well webpack-dev-server 1.14 shows warn on `npm i`  that it required webpack 1.*
you are using 2.* 
you can safely bump version of webpack-dev-server to 2*-beta. it works fine

**Comment by peter-mouland** [comment]
Maybe the packages have been mixed swapping branches?

The only branch with webpack-dev-server is master and that does not use webpack2.
Webpack2 branch uses express so it does not have webpack-dev-server.
perhaps do `rm -rf node_modules && npm i` and let me know if you still have the same problem?

**Comment by dlebedynskyi** [comment]
@peter-mouland sorry for bad description earlier. was a bit in a rush. 
I'm talking about this branch
https://github.com/peter-mouland/react-lego/blob/webpack2-rhl/package.json#L102
I believe it should be something like this 
```
   "webpack": "2.1.0-beta.25",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-dev-server": "^2.1.0-beta.8",
    "webpack-hot-middleware": "^2.12.2"
```

**Comment by peter-mouland** [comment]
ah - i get you. sorry for being a bit slow!

I've updated that branch now. thanks 👍
