### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@2.1.0-beta.22

### ISSUE THREAD

**Issue by tuler** [peter-mouland/react-lego#3]
from a clean clone of branch `webpack2-rhl`.

```
node --version
v6.3.0
```
```
npm --version
3.10.7
```

**Comment by peter-mouland** [comment]
hmm... not sure how you got that error. i just tried it again and got the following warning:
`webpack-dev-server@1.15.2 requires a peer of webpack@>=1.3.0 <3 but none was installed.`

i executed the following:
`git checkout webpack2-rhl && rm -rf node_modules && npm i && npm run start:dev`

Everything seems ok to me.

Does the warning mean the branch doesn't work for you?

**Comment by tuler** [comment]
Indeed it's just a warning.
Is it possible to get rid of it?

**Comment by peter-mouland** [comment]
This is a npm warning so you'd have to speak to them about how to suppress it.
